class Constants {
  static List followingl = [];
  static List stockl = [
    'HINDUNILVR',
    'ZEEL',
    'TATAMOTORS',
    'BPCL',
    'HDFCBANK',
    'BRITANNIA',
    'BAJAJ-AUTO',
    'TITAN',
    'KOTAKBANK',
    'BAJFINANCE',
    'TCS',
    'HEROMOTOCO',
    'VEDL',
    'POWERGRID',
    'BAJAJFINSV',
    'SBIN',
    'SHREECEM',
    'GRASIM',
    'UPL',
    'HINDALCO',
    'ADANIPORTS',
    'ONGC',
    'INDUSINDBK',
    'COALINDIA',
    'MARUTI',
    'MM',
    'ITC',
    'TECHM',
    'TATASTEEL',
    'NESTLEIND',
    'ULTRACEMCO',
    'JSWSTEEL',
    'INFY',
    'SUNPHARMA',
    'NTPC',
    'CIPLA',
    'HDFC',
    'GAIL',
    'DRREDDY',
    'IOC',
    'LT',
    'HCLTECH',
    'AXISBANK',
    'BHARTIARTL',
    'RELIANCE',
    'ASIANPAINT',
    'WIPRO',
    'ICICIBANK',
    'EICHERMOT'
  ];
  static var stockd = {
    'ADANIPORTS': 'Adani Ports and Special Economic Zone Ltd.',
    'ASIANPAINT': 'Asian Paints Ltd.',
    'AXISBANK': 'Axis Bank Ltd.',
    'BAJAJ-AUTO': 'Bajaj Auto Ltd.',
    'BAJAJFINSV': 'Bajaj Finserv Ltd.',
    'BAJFINANCE': 'Bajaj Finance Ltd.',
    'BHARTIARTL': 'Bharti Airtel Ltd.',
    'BPCL': 'Bharat Petroleum Corporation Ltd.',
    'BRITANNIA': 'Britannia Industries Ltd.',
    'CIPLA': 'Cipla Ltd.',
    'COALINDIA': 'Coal India Ltd.',
    'DRREDDY': "Dr. Reddy's Laboratories Ltd.",
    'EICHERMOT': 'Eicher Motors Ltd.',
    'GAIL': 'GAIL (India) Ltd.',
    'GRASIM': 'Grasim Industries Ltd.',
    'HCLTECH': 'HCL Technologies Ltd.',
    'HDFC': 'Housing Development Finance Corporation Ltd.',
    'HDFCBANK': 'HDFC Bank Ltd.',
    'HEROMOTOCO': 'Hero MotoCorp Ltd.',
    'HINDALCO': 'Hindalco Industries Ltd.',
    'HINDUNILVR': 'Hindustan Unilever Ltd.',
    'ICICIBANK': 'ICICI Bank Ltd.',
    'INDUSINDBK': 'IndusInd Bank Ltd.',
    'INFY': 'Infosys Ltd.',
    'IOC': 'Indian Oil Corporation Ltd.',
    'ITC': 'ITC Ltd.',
    'JSWSTEEL': 'JSW Steel Ltd.',
    'KOTAKBANK': 'Kotak Mahindra Bank Ltd.',
    'LT': 'Larsen & Toubro Ltd.',
    'MM': 'Mahindra & Mahindra Ltd.',
    'MARUTI': 'Maruti Suzuki India Ltd.',
    'NESTLEIND': 'Nestle India Ltd.',
    'NTPC': 'NTPC Ltd.',
    'ONGC': 'Oil & Natural Gas Corporation Ltd.',
    'POWERGRID': 'Power Grid Corporation of India Ltd.',
    'RELIANCE': 'Reliance Industries Ltd.',
    'SBIN': 'State Bank of India',
    'SHREECEM': 'Shree Cement Ltd.',
    'SUNPHARMA': 'Sun Pharmaceutical Industries Ltd.',
    'TATAMOTORS': 'Tata Motors Ltd.',
    'TATASTEEL': 'Tata Steel Ltd.',
    'TCS': 'Tata Consultancy Services Ltd.',
    'TECHM': 'Tech Mahindra Ltd.',
    'TITAN': 'Titan Company Ltd.',
    'ULTRACEMCO': 'UltraTech Cement Ltd.',
    'UPL': 'UPL Ltd.',
    'VEDL': 'Vedanta Ltd.',
    'WIPRO': 'Wipro Ltd.',
    'ZEEL': 'Zee Entertainment Enterprises Ltd.'
  };
}
